apiVersion: v1
kind: Pod
metadata:
  name: web-db
spec:
  containers:
  - name: nginx
    image: nginx:1.17-alpine
  - name: redis
    image: redis:5.0.8-alpine
    env:
    - name: FOO
      value: "bar"
